//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEORDEN
    {
        public int ID_DETALLE { get; set; }
        public int ID_ORDEN { get; set; }
        public int ID_TRABAJO { get; set; }
        public Nullable<int> ID_MATERIAL { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual MATERIALES MATERIALES { get; set; }
        public virtual ORDENTRABAJO ORDENTRABAJO { get; set; }
        public virtual TRABAJOSREALIZADOS TRABAJOSREALIZADOS { get; set; }
    }
}
