//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.SOLIORDEN = new HashSet<SOLIORDEN>();
            this.ORDENTRABAJO = new HashSet<ORDENTRABAJO>();
        }
    
        public int ID_EMPLE { get; set; }
        public string DNI { get; set; }
        public string NON { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<byte> ID_CARGO { get; set; }
        public Nullable<byte> ID_DEPARTA { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLIORDEN> SOLIORDEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENTRABAJO> ORDENTRABAJO { get; set; }
    }
}
