//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENTRABAJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDENTRABAJO()
        {
            this.DETALLEORDEN = new HashSet<DETALLEORDEN>();
        }
    
        public int ID_ORDEN { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHAFINAL { get; set; }
        public Nullable<int> ID_EMPLE { get; set; }
        public Nullable<byte> ID_MANTENI { get; set; }
        public Nullable<int> ID_SOLIORDEN { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual MANTENIMIENTO MANTENIMIENTO { get; set; }
        public virtual SOLIORDEN SOLIORDEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEORDEN> DETALLEORDEN { get; set; }
    }
}
